// client/src/App.tsx
import { useEffect, useMemo } from 'react';
import githubLogo from './assets/githublogo.svg';
import Footer from './components/Footer';
import Hero from './components/Hero';
import Navigation from './components/Navigation';
import { useWebRTCController } from './hooks/useWebRTCController';
import { WebRTCController } from './services/webrtccontroller';
import { generateName, getAgentInfo } from './utilis/uaNames';

export default function App() {
  const localAlias = useMemo(() => generateName(), []);
  const localDevice = useMemo(() => getAgentInfo(navigator.userAgent), []);
  const controller = useMemo(() => new WebRTCController(localAlias, localDevice), [localAlias, localDevice]);
  const state = useWebRTCController(controller);

  useEffect(() => {
    return () => controller.destroy();
  }, [controller]);

  return (
    <div className="flex min-h-screen flex-col">
      <Navigation logoSrc={githubLogo} />
      <Hero
        alias={state.myName || localAlias}
        peers={state.peers}
        connectionStatus={state.connectionStatus}
        connectionLabel={(peerId) => controller.connectionLabel(peerId)}
        onSendFiles={(peerId, files) => controller.sendFiles(peerId, files)}
      />
      <div className="mt-auto">
        <Footer />
      </div>
    </div>
  );
}

// client/src/App.svelte
<script lang="ts">
	import './app.css';
	import { onDestroy } from 'svelte';
	import { WebRTCController } from './services/webrtccontroller.svelte';
	import { generateName, getAgentInfo } from './utilis/uaNames';
	import Footer from './lib/Footer.svelte';
	import Hero from '$lib/components/Hero.svelte';
	import Navigation from '$lib/components/Navigation.svelte';
	import slika from './assets/githublogo.svg';

	const localAlias = generateName();
	const localDevice = getAgentInfo(navigator.userAgent);
	const controller = new WebRTCController(localAlias, localDevice);

	function sendFiles(peerId: string, files: FileList): void {
		controller.sendFiles(peerId, files);
	}

	onDestroy(() => {
		controller.destroy();
	});
</script>

<div class="flex min-h-screen flex-col">
	<Navigation logoSrc={slika} />

	<Hero
		alias={controller.myName || localAlias}
		animationSrc="/hellodog.png"
		peers={controller.peers.filter((peer) => controller.isPeerConnected(peer.id))}
		connectionStatus={controller.connectionStatus}
		connectionLabel={(peerId) => controller.connectionLabel(peerId)}
		onSendFiles={sendFiles}
	/>

	<div class="mt-auto">
		<Footer />
	</div>
</div>
