// client/src/lib/components/Navigation.svelte
<script lang="ts">
	import { cn } from "$lib/utils.js";

	export let logoSrc = "";
	export let logoAlt = "Ollama";
	export let aboutHref = "#";
	export let className = "";
</script>

<header
	data-slot="navigation"
	class={cn("sticky top-0 z-50 w-full  bg-background", className)}
>
	<nav class="flex w-full items-center justify-start px-6 py-4">
		<div class="flex items-center gap-6">
			{#if logoSrc}
				<a href="https://github.com/imim77/filesender" target="_blank" rel="noopener noreferrer" class="focus-visible:ring-ring/50 rounded-sm outline-none transition-colors focus-visible:ring-[3px]">
					<img src={logoSrc} alt={logoAlt} class="h-12" />
				</a>
			{/if}
			<a
				href={aboutHref}
				class="focus-visible:border-ring focus-visible:ring-ring/50 rounded-sm text-base font-medium text-foreground transition-colors outline-none hover:text-muted-foreground focus-visible:ring-[3px]"
			>
				About project
			</a>
		</div>
	</nav>
</header>

// client/src/components/Navigation.tsx
type NavigationProps = {
  logoSrc?: string;
  logoAlt?: string;
  aboutHref?: string;
  className?: string;
};

export default function Navigation({
  logoSrc = '',
  logoAlt = 'Filesender',
  aboutHref = '#',
  className = '',
}: NavigationProps) {
  return (
    <header data-slot="navigation" className={`sticky top-0 z-50 w-full bg-background ${className}`.trim()}>
      <nav className="flex w-full items-center justify-start px-6 py-4">
        <div className="flex items-center gap-6">
          {logoSrc ? (
            <a
              href="https://github.com/imim77/filesender"
              target="_blank"
              rel="noopener noreferrer"
              className="rounded-sm outline-none transition-colors focus-visible:ring-3 focus-visible:ring-ring/50"
            >
              <img src={logoSrc} alt={logoAlt} className="h-12" />
            </a>
          ) : null}
          <a
            href={aboutHref}
            className="rounded-sm text-base font-medium text-foreground outline-none transition-colors hover:text-muted-foreground focus-visible:ring-3 focus-visible:ring-ring/50"
          >
            About project
          </a>
        </div>
      </nav>
    </header>
  );
}
